# Miscellaneous
analytics: UA-106429071-3
favicon: /favicon.png
twitter: https://twitter.com/sidon_song
gmail: mailto:master@ssch.me
github: https://github.com/ssghost
youtube: https://www.youtube.com/channel/UCFTdY6Vlx6AJC8VGytssh6w
